name: kotgltd
description: King of the Grid Community App

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # add_2_calendar: ^2.1.1
  # external_app_launcher: ^2.0.0
  # flutter_local_notifications: ^9.0.0-dev.4
  scroll_date_picker: ^3.4.0
  animate_do: ^2.0.0
  badges: ^2.0.1
  cached_network_image: ^3.1.0
  card_swiper: ^2.0.1
  connectivity_plus: ^2.2.0
  custom_navigation_bar: ^0.8.1
  dart_date: ^1.1.0
  modal_bottom_sheet: ^2.1.0
  awesome_snackbar_content: ^0.0.5
  date_picker_timeline: ^1.2.3
  flip_card: ^0.6.0
  date_time_picker: ^2.1.0
  go_router: ^4.1.0
  dotenv: ^3.0.0-nullsafety.0
  email_validator: ^2.0.1
  envify: ^2.0.0
  extended_image: ^6.0.1
  file_picker: ^4.5.1
  fl_chart: ^0.41.0
  flutter_easyloading: ^3.0.0
  flutter_markdown: ^0.6.7
  flutter_slidable: ^1.2.0
  colorize_text_avatar: ^1.0.2
  fluttertoast: ^8.0.8
  gaimon: ^1.0.0+2
  google_fonts: ^2.1.0
  graphql: ^5.0.1
  hive_flutter: ^1.0.0
  hive: ^2.0.4
  hooks_riverpod: ^1.0.0
  http: ^0.13.3
  intl_phone_number_input: ^0.7.0+2
  ionicons: ^0.1.2
  jiffy: ^5.0.0
  json_annotation: ^4.0.1
  jwt_decoder: ^2.0.1
  line_icons: ^2.0.1
  loader_overlay: ^2.0.2
  loading_indicator: ^3.0.1
  lottie: ^1.1.0
  percent_indicator: ^4.0.0
  permission_handler: ^9.2.0
  phone_form_field: ^6.1.0
  qr_flutter: ^4.0.0
  share_plus: ^3.0.4
  sizer: ^2.0.15
  skeleton_animation: ^0.1.4
  throttling: ^1.0.0
  ticket_material: ^0.3.1
  timeago: ^3.2.2
  uuid: ^3.0.4
  validators: ^3.0.0
  url_launcher: ^6.1.3
  flutter_automation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  build_web_compilers: ^3.0.0
  envify_generator: ^2.0.0
  hive_generator: ^1.1.2
  json_serializable: ^6.1.4
  lints: ^1.0.1
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  image_path: "assets/icon/Icon.png"
  android: "launcher_icon"
  ios: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
